import Head from "next/head";
import Website from "@/components/Website";

export default function Home() {
	return (
		<>
			<Head>
				<title>Unbearable Dev</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Website />
		</>
	);
}
